.\" Copyright (c) 2014 Martin Natano <natano@natano.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: June 7 2014 $
.Dt RDCONFIG 8
.Os
.Sh NAME
.Nm rdconfig
.Nd configure kernel image for usage with tmpfsrd
.Sh SYNOPSIS
.Nm rdconfig
.Op Fl fIX
.Ar kernel
.Op Ar fs
.Sh DESCRIPTION
The
.Nm
utility allows manipulation of a special
.Xr elf 5
segment inside of kernel images dedicated for usage by
.Xr tmpfsrd 4 .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f
Replace existing elf segment instead of inserting a new one.
Overwrite
.Ar fs
when combined with the
.Fl X
option.
.It Fl I
Check the
.Ar kernel
for known unbootable configurations.
.It Fl X
Extract tmpfs snapshot from
.Ar kernel
and write it to
.Ar fs
when specified, or standard output otherwise.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr config 8
.Sh HISTORY
The
.Nm
utility appeared in
.Br 0.1.
