#	$OpenBSD: Makefile,v 1.19 2013/10/31 01:24:06 bluhm Exp $
#	$NetBSD: Makefile,v 1.4 1995/04/20 22:41:08 cgd Exp $

SUBDIR+= copy crypto ddb fifofs fs-snapshot kern net netinet6 ptrace sys uvm dev

install:

.include <bsd.subdir.mk>
