# $FreeBSD$

.include <bsd.own.mk>

LIB=	clangrewrite

SRCDIR=	tools/clang/lib/Rewrite
SRCS=	DeltaTree.cpp \
	HTMLRewrite.cpp \
	RewriteRope.cpp \
	Rewriter.cpp \
	TokenRewriter.cpp

TGHDRS=	DiagnosticCommonKinds

.include "../clang.lib.mk"
