# $FreeBSD$

.include <bsd.own.mk>

LIB=	llvmprofiledata

SRCDIR=	lib/ProfileData
SRCS=	InstrProf.cpp \
	InstrProfReader.cpp \
	InstrProfWriter.cpp \
	CoverageMapping.cpp \
	CoverageMappingWriter.cpp \
	CoverageMappingReader.cpp \
	SampleProf.cpp \
	SampleProfReader.cpp \
	SampleProfWriter.cpp

TGHDRS=

.include "../clang.lib.mk"
