# Copyright (C) 1989-2000, 2003, 2009 Free Software Foundation, Inc.
#      Written by James Clark (jjc@jclark.com)
# 
# This file is part of groff.
# 
# groff is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# groff is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Makefile.lib
#
LIBCLEAN=lib$(LIB).$(LIBEXT)
MAKEFILEPARTS=\
  $(top_srcdir)/Makefile.comm \
  $(top_builddir)/Makefile.cfg \
  $(srcdir)/Makefile.sub \
  $(top_srcdir)/Makefile.lib \
  Makefile.dep

all: lib$(LIB).$(LIBEXT)

lib$(LIB).$(LIBEXT): $(OBJS)
	$(AR) r $@ $?
	$(RANLIB) $@

depend: depend_src
depend.temp: $(GENSRCS)
TAGS: $(CCSRCS) $(CSRCS)
Makefile: $(MAKEFILEPARTS)
Makefile.dep:
	touch Makefile.dep
