#	$OpenBSD: Makefile,v 1.55 2014/07/16 01:23:39 deraadt Exp $
#	$NetBSD: Makefile,v 1.35 1996/04/03 21:20:52 chuck Exp $

.include <bsd.own.mk>

SUBDIR+=	texinfo
SUBDIR+=	perl

.include <bsd.subdir.mk>
