/* u_concat.t:  Invalid pp-token generated by ## operator.  */
#define _VARIANT_BOOL   /##/
/*
 *   The following line intends to be commented out.  '//' generated by the
 * macro is, however, not a valid pp-token.  Since any comment is removed
 * before macro definition or macro expansion, a comment is never generated
 * by macro.
 */
    _VARIANT_BOOL bool;

