#	$OpenBSD: Makefile,v 1.3 2000/05/15 03:37:32 millert Exp $

PROG=	editmap
MAN=	editmap.8
ENVDEF=	-DNOT_SENDMAIL

WANT_LIBSM=1
WANT_LIBSMDB=1
WANT_LIBSMUTIL=1

.include "../../Makefile.inc"
.include <bsd.prog.mk>
