#	$OpenBSD: Makefile,v 1.33 2014/07/24 19:21:48 miod Exp $

SUBDIR=	libstubs \
	arch date dd dhclient dmesg ed grep gzip ifconfig init \
	installboot kbd md5 more mt newfs pax ping pwd_mkdb restore \
	sed sysctl signify umount

install:

.include <bsd.subdir.mk>
