# $FreeBSD$

.include <bsd.own.mk>

LIB=	llvmbitreader

SRCDIR=	lib/Bitcode/Reader
SRCS=	BitReader.cpp \
	BitcodeReader.cpp \
	BitstreamReader.cpp

TGHDRS=	Attributes \
	Intrinsics

.include "../clang.lib.mk"
